[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
root = "/backend"

[services.env]
NODE_ENV = "production"
PORT = "${{PORT}}"
FRONTEND_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
VALHALLA_URL = "https://valhalla1.openstreetmap.de"
# For local Valhalla deployment:
# VALHALLA_URL = "http://${{vahalla.RAILWAY_PRIVATE_DOMAIN}}:8002"